import { Inter} from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import {Toaster} from "react-hot-toast";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Trupti",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.variable} antialiased`}>
         
          <Toaster 
            toastOptions={{
              success: { style: {background: "black", color: "white"}},
              error: { style: {background: "black", color: "white"}}
            }}
          />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
